name: url_tinyfier
description: An app for creating short URLs written in Flutter.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  http: ^0.12.0
  url_launcher: 4.0.1
  flutter:
    sdk: flutter
  shared_preferences: 0.4.3
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
flutter_icons:
  android: true 
  ios: false
  image_path: "assets/icon/urlIcon.png"
flutter:
  uses-material-design: true
  assets:
      - assets/icon/urlIcon.png